#index:
#    path: /
#    controller: App\Controller\DefaultController::index
ListContainers:
  path: /container
  controller: App\Controller\ContainerController::ListContainers
  methods: GET

GetContainer:
  path: /container/{id}
  controller: App\Controller\ContainerController::GetContainer
  methods: GET
  requirements:
    id: \d+

ListContainerShips:
  path: /containership
  controller: App\Controller\ContainerShipController::ListContainerShips
  methods: GET

GetContainerShip:
  path: /containership/{id}
  controller: App\Controller\ContainerShipController::GetContainerShip
  methods: GET
  requirements:
    id: \d+

ListProducts:
  path: /product
  controller: App\Controller\ProductController::ListProducts
  methods: GET

GetProduct:
  path: /product/{id}
  controller: App\Controller\ProductController::GetProduct
  methods: GET
  requirements:
    id: \d+